[project]
name =  "deep-learning-toolkit"
version = "0.4.1"
authors = [
    { name = "Johann Rudi", email = "jrudi@vt.edu" },
]
description = "Deep Learning Toolkit — Reusable PyTorch building blocks for artificial intelligence & scientific machine learning: networks, losses, training loops, and utilities."
readme = "README.md"
license = "GPL-3.0-only"
license-files = ["LICEN[CS]E*"]
classifiers = [
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
]
keywords = [
    "artificial intelligence",
    "deep learning",
    "machine learning",
    "neural networks",
    "scientific computing",
    "pytorch",
]
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3,<4",
    "prettytable>=3,<4",
    "pyyaml>=6,<7",
    "torch>=2,<3",
    "tqdm>=4,<5",
]

[dependency-groups]
dev = [
    "basedpyright>=1.39,<2",
    "black>=25,<26",
    "build>=1.5.0,<2",
    "bumpver>=2026",
    "flow-matching>=1.0.10,<2",
    "isort>=5,<6",
    "pip-tools>=7,<8",
    "pytest>=8,<9",
    "torch-kde>=0.1.5",
    "twine>=7,<8",
]
diffusion = [
    "flow-matching>=1.0.10,<2",
]
kde = [
    "torch-kde>=0.1.5",
]
test = [
    "pytest>=8,<9",
]

[project.urls]
Homepage = "https://github.com/johannrudi/deep-learning-toolkit"
Repository = "https://github.com/johannrudi/deep-learning-toolkit"
Issues = "https://github.com/johannrudi/deep-learning-toolkit/issues"

#[project.scripts]
#dlk = "dlk.__main__:main"

# --------------------------------------
# Tools
# --------------------------------------

[tool.basedpyright]
pythonVersion = "3.11"
typeCheckingMode = "basic"
venvPath = "."
venv = ".venv"

[tool.black]
line-length = 88
target-version = ["py311"]

[tool.bumpver]
current_version = "0.4.1"
version_pattern = "MAJOR.MINOR.PATCH"
commit_message = "Bump version {old_version} -> {new_version}"
tag_name = "v{new_version}"
commit = true
tag = false
push = false

[tool.bumpver.file_patterns]
"pyproject.toml" = [
    'current_version = "{version}"',
    'version = "{version}"',
]
"dlk/__init__.py" = [
    '__version__ = "{version}"',
]

[tool.isort]
profile = "black"
src_paths = ["dlk", "tests"]

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "-ra"

# --------------------------------------
# Build System
# --------------------------------------

[build-system]
requires = ["setuptools>=77", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["dlk*"]
exclude = ["tests*", "_*"]
namespaces = false  # do not add folders without `__init__.py` file
