"""Regression tests freezing single-process loss trajectories of the train loops.

The expected values below were generated with this file's `__main__` entry point
(`python tests/opt/test_train_single_process_regression.py`) before the DDP
refactoring. They pin the exact single-process behavior of
`dlk.opt.train.train_epochs` and `dlk.opt.train_gan.train_epochs` on CPU; the
DDP changes must not alter them. Regenerate on torch version bumps.

Fixed seeds make both runs bit-reproducible on a given machine and torch build,
but not necessarily across CI runners: MKL/oneDNN pick different vectorized
kernels depending on the host CPU's instruction set, and floating-point
summation is not associative, so matmul/reduction results can differ in their
last few bits across hardware even with identical seeds. `_single_threaded_torch`
removes intra-op reduction-order nondeterminism as one contributing factor, and
the assertions below use a tolerance wide enough to absorb the remaining
cross-hardware noise without masking real regressions.
"""

import contextlib
from collections.abc import Iterator

import pytest
import torch

from dlk.opt.train import train_epochs as train_epochs_supervised
from dlk.opt.train_gan import train_epochs as train_epochs_gan

# relative tolerance covers cross-hardware floating-point noise (observed up to
# ~3e-6) while still catching genuine algorithmic regressions
REGRESSION_RTOL = 1e-4


@contextlib.contextmanager
def _single_threaded_torch() -> Iterator[None]:
    """Force single-threaded CPU ops to remove one source of reduction-order noise."""
    prev_num_threads = torch.get_num_threads()
    torch.set_num_threads(1)
    try:
        yield
    finally:
        torch.set_num_threads(prev_num_threads)


# expected loss trajectories; generated by the __main__ entry point (torch 2.13.0, CPU)
EXPECTED_SUPERVISED_LOSS_MEAN = [
    1.1506327986717224,
    0.9840117990970612,
    0.8984898179769516,
]
EXPECTED_GAN_G_LOSS_MEAN = [
    -0.28841303288936615,
    -0.15045922435820103,
]
EXPECTED_GAN_D_PRE_LOSS_MEAN = [
    -0.006984345614910126,
    -0.09895740449428558,
]


def _make_supervised_dataloader() -> torch.utils.data.DataLoader:
    """Build a deterministic dataloader for the supervised regression run."""
    generator = torch.Generator().manual_seed(1234)
    features = torch.randn((32, 4), generator=generator, dtype=torch.float32)
    targets = torch.randn((32, 2), generator=generator, dtype=torch.float32)
    dataset = torch.utils.data.TensorDataset(features, targets)
    return torch.utils.data.DataLoader(dataset, batch_size=8, shuffle=False)


def _run_supervised_training() -> list[float]:
    """Train a small MLP with fixed seeds and return the loss-mean trajectory."""
    with _single_threaded_torch():
        torch.manual_seed(42)
        net = torch.nn.Sequential(
            torch.nn.Linear(4, 8),
            torch.nn.Tanh(),
            torch.nn.Linear(8, 2),
        )
        optimizer = torch.optim.SGD(net.parameters(), lr=0.1)
        epoch_dlog = train_epochs_supervised(
            n_epochs=3,
            net=net,
            dataloader=_make_supervised_dataloader(),
            optimizer=optimizer,
            loss_fn=torch.nn.MSELoss(),
        )
        return [float(v) for v in epoch_dlog["loss_mean"]]


class _Generator(torch.nn.Module):
    """Tiny conditional generator mapping `(y, z)` to samples."""

    def __init__(self) -> None:
        super().__init__()
        self.layers = torch.nn.Sequential(
            torch.nn.Linear(3 + 2, 8),
            torch.nn.Tanh(),
            torch.nn.Linear(8, 4),
        )

    def forward(self, y: torch.Tensor, z: torch.Tensor) -> torch.Tensor:
        assert y.dim() == 2 and z.dim() == 2, (
            f"expected 2D conditioning and latent tensors, "
            f"got shapes {tuple(y.shape)} and {tuple(z.shape)}"
        )
        return self.layers(torch.cat((y, z), dim=1))


class _Discriminator(torch.nn.Module):
    """Tiny conditional discriminator mapping `(x, y)` to a score."""

    def __init__(self) -> None:
        super().__init__()
        self.layers = torch.nn.Sequential(
            torch.nn.Linear(4 + 3, 8),
            torch.nn.Tanh(),
            torch.nn.Linear(8, 1),
        )

    def forward(self, x: torch.Tensor, y: torch.Tensor) -> torch.Tensor:
        assert x.dim() == 2 and y.dim() == 2, (
            f"expected 2D sample and conditioning tensors, "
            f"got shapes {tuple(x.shape)} and {tuple(y.shape)}"
        )
        return self.layers(torch.cat((x, y), dim=1))


def _gan_loss_fn(
    d_outputs_gen: torch.Tensor,
    d_outputs_data: torch.Tensor | None,
) -> tuple[torch.Tensor, torch.Tensor | None]:
    """Compute a Wasserstein-style loss for discriminator and generator steps."""
    loss_g = -d_outputs_gen.mean()
    if d_outputs_data is None:
        return loss_g, None
    return d_outputs_gen.mean() - d_outputs_data.mean(), loss_g


def _d_reg_fn(
    d_net: torch.nn.Module,
    x_gen: torch.Tensor,
    x_data: torch.Tensor,
    y_data: torch.Tensor,
    *,
    dlog: dict[str, float] | None = None,
) -> torch.Tensor:
    """Compute a simple squared-output discriminator penalty."""
    penalty = 0.1 * d_net(x_data, y_data).square().mean()
    if dlog is not None:
        dlog["reg"] = penalty.item()
    return penalty


def _make_gan_dataloader() -> torch.utils.data.DataLoader:
    """Build a deterministic dataloader for the GAN regression run."""
    generator = torch.Generator().manual_seed(5678)
    x_data = torch.randn((32, 4), generator=generator, dtype=torch.float32)
    y_data = torch.randn((32, 3), generator=generator, dtype=torch.float32)
    dataset = torch.utils.data.TensorDataset(x_data, y_data)
    return torch.utils.data.DataLoader(dataset, batch_size=8, shuffle=False)


def _run_gan_training() -> tuple[list[float], list[float]]:
    """Train a tiny GAN with fixed seeds and return loss-mean trajectories."""
    with _single_threaded_torch():
        torch.manual_seed(42)
        g_net = _Generator()
        d_net = _Discriminator()
        g_optimizer = torch.optim.SGD(g_net.parameters(), lr=0.05)
        d_optimizer = torch.optim.SGD(d_net.parameters(), lr=0.05)
        epoch_dlog = train_epochs_gan(
            n_epochs=2,
            g_net=g_net,
            d_net=d_net,
            dataloader=_make_gan_dataloader(),
            z_sample_fn=lambda batch_size: torch.randn((batch_size, 2)),
            g_optimizer=g_optimizer,
            d_optimizer=d_optimizer,
            loss_fn=_gan_loss_fn,
            d_reg_fn=_d_reg_fn,
            d_opt_pre=2,
            d_opt_post=1,
        )
        g_loss = [float(v) for v in epoch_dlog["g_loss_mean"]]
        d_pre_loss = [float(v) for v in epoch_dlog["d_pre_loss_mean"]]
        return g_loss, d_pre_loss


def test_supervised_training_loss_trajectory_is_unchanged() -> None:
    """Reproduce the frozen loss trajectory of `train.train_epochs`."""
    loss_mean = _run_supervised_training()

    assert loss_mean == pytest.approx(
        EXPECTED_SUPERVISED_LOSS_MEAN, rel=REGRESSION_RTOL
    )


def test_gan_training_loss_trajectories_are_unchanged() -> None:
    """Reproduce the frozen loss trajectories of `train_gan.train_epochs`."""
    g_loss_mean, d_pre_loss_mean = _run_gan_training()

    assert g_loss_mean == pytest.approx(EXPECTED_GAN_G_LOSS_MEAN, rel=REGRESSION_RTOL)
    assert d_pre_loss_mean == pytest.approx(
        EXPECTED_GAN_D_PRE_LOSS_MEAN, rel=REGRESSION_RTOL
    )


if __name__ == "__main__":
    # regenerate the expected trajectories
    print("EXPECTED_SUPERVISED_LOSS_MEAN =", _run_supervised_training())
    g_loss_mean_, d_pre_loss_mean_ = _run_gan_training()
    print("EXPECTED_GAN_G_LOSS_MEAN =", g_loss_mean_)
    print("EXPECTED_GAN_D_PRE_LOSS_MEAN =", d_pre_loss_mean_)
