"""Regression tests freezing the autograd gradient penalty in `dlk.loss.gradient_penalty`.

The expected values below were generated with this file's `__main__` entry point
(`python tests/loss/test_gradient_penalty_regression.py`) before the Lipschitz
regularization work of plan `2026.008`, from the former `gradient_penalty_lip`
and `gradient_penalty_opt`. `gradient_penalty` reproduces them, up to its factor
`PENALTY_SCALE = 1/2`, with the arguments in `CASES`: a `relu` nonlinearity and
`eps=0` for the one-sided penalty, and `eps=1e-12` (the former square-root
guard) for the two-sided one. Regenerate on torch version bumps.

Frozen per case: the scalar penalty value and, for each critic parameter, its
full flattened `.grad`. `_single_threaded_torch` removes intra-op
reduction-order nondeterminism as one source of cross-hardware floating-point
noise, and the assertions below use a tolerance wide enough to absorb the
remaining noise without masking a real regression.
"""

import contextlib
from collections.abc import Iterator
from typing import Any

import pytest
import torch
import torch.nn.functional as F

from dlk.loss.gradient_penalty import gradient_penalty

# relative tolerance covers cross-hardware floating-point noise; absolute
# tolerance covers values near zero, where a relative tolerance is too tight
REGRESSION_RTOL = 1e-4
REGRESSION_ATOL = 1e-7

BATCH_SIZE = 8
X_SIZE = 3
Y_SIZE = 2
LIP = 0.3  # small enough that the relu is active for some samples
SEED = 0

# `gradient_penalty` scales by 1/2; the frozen values below predate that factor
PENALTY_SCALE = 0.5


@contextlib.contextmanager
def _single_threaded_torch() -> Iterator[None]:
    """Force single-threaded CPU ops to remove one source of reduction-order noise."""
    prev_num_threads = torch.get_num_threads()
    torch.set_num_threads(1)
    try:
        yield
    finally:
        torch.set_num_threads(prev_num_threads)


class _Critic(torch.nn.Module):
    """Small MLP critic scoring `x`, or `(x, y)` pairs when conditional."""

    def __init__(self, conditional: bool) -> None:
        super().__init__()
        self.conditional = conditional
        input_size = X_SIZE + Y_SIZE if conditional else X_SIZE
        self.net = torch.nn.Sequential(
            torch.nn.Linear(input_size, 16),
            torch.nn.Tanh(),
            torch.nn.Linear(16, 1),
        )

    def forward(self, x: torch.Tensor, y: torch.Tensor | None = None) -> torch.Tensor:
        """Score `x` alone, or `torch.cat([x, y], dim=1)` when conditional."""
        if self.conditional:
            assert y is not None, "conditional critic requires `y`"
            x = torch.cat([x, y], dim=1)
        return self.net(x)


ONE_SIDED_RELU_KWARGS: dict[str, Any] = {
    "lip": LIP,
    "eps": 0.0,
    "one_sided_nonlinearity": F.relu,
}
TWO_SIDED_KWARGS: dict[str, Any] = {"one_sided": False, "eps": 1e-12}

# map each case name to its conditionality and `gradient_penalty` kwargs
CASES: dict[str, tuple[bool, dict[str, Any]]] = {
    "one_sided_relu_conditional": (True, ONE_SIDED_RELU_KWARGS),
    "one_sided_relu_unconditional": (False, ONE_SIDED_RELU_KWARGS),
    "two_sided_conditional": (True, TWO_SIDED_KWARGS),
    "two_sided_unconditional": (False, TWO_SIDED_KWARGS),
}

# expected values; generated by the __main__ entry point (torch 2.13.0+cu130, CPU)
EXPECTED_VALUE: dict[str, float] = {
    "one_sided_relu_conditional": 0.006940653547644615,
    "one_sided_relu_unconditional": 0.008416412398219109,
    "two_sided_conditional": 0.5034021735191345,
    "two_sided_unconditional": 0.5002790689468384,
}
EXPECTED_GRADS: dict[str, list[list[float]]] = {
    "one_sided_relu_conditional": [
        [
            0.011166829615831375,
            0.009562208317220211,
            -0.0033034842927008867,
            0.010390366427600384,
            0.0021432165522128344,
            0.005724554415792227,
            0.0039420053362846375,
            -0.0011398645583540201,
            0.00586277898401022,
            0.0012677510967478156,
            -0.026787186041474342,
            -0.01649302802979946,
            0.006481608375906944,
            -0.03184554725885391,
            -0.0053825052455067635,
            -0.012949097901582718,
            -0.011884195730090141,
            0.005003979429602623,
            -0.013954638503491879,
            0.00012605171650648117,
            0.030910054221749306,
            0.006235569715499878,
            -0.005530752707272768,
            0.03994852304458618,
            -0.007168431766331196,
            0.018496062606573105,
            0.011639758013188839,
            -0.004277792759239674,
            0.017421051859855652,
            0.0024991370737552643,
            -0.011534574441611767,
            -0.009988423436880112,
            0.003232875606045127,
            -0.010801181197166443,
            -0.002728923922404647,
            -0.00760972173884511,
            -0.004656934179365635,
            0.0021522571332752705,
            -0.009253572672605515,
            -0.000684855505824089,
            -0.028796203434467316,
            -0.0023447293788194656,
            0.0036859912797808647,
            -0.03667628765106201,
            0.007279497571289539,
            -0.0004761191667057574,
            -0.0005075812805444002,
            0.00018545627244748175,
            -0.0004969233414158225,
            -0.00013836384459864348,
            -0.009235747158527374,
            0.0018300646916031837,
            0.0035646369215101004,
            -0.020335335284471512,
            0.008834073320031166,
            -0.024337712675333023,
            -0.023724719882011414,
            0.008289813064038754,
            -0.026751525700092316,
            -0.006332875229418278,
            -0.001110729412175715,
            -0.0005232248804531991,
            0.00039016641676425934,
            -0.0017275700811296701,
            0.0004782743635587394,
            0.0035113494377583265,
            0.002920981962233782,
            -0.001157131278887391,
            0.004136537201702595,
            6.502523319795728e-05,
            -0.013867471367120743,
            -0.010614614002406597,
            0.0034551036078482866,
            -0.014902422204613686,
            -0.0038218824192881584,
            0.016626974567770958,
            0.01047701109200716,
            -0.0027584426570683718,
            0.018712645396590233,
            0.011159875430166721,
        ],
        [
            -0.0013877305900678039,
            -5.982141010463238e-05,
            -0.0012681230437010527,
            0.004547445103526115,
            -0.0012002077419310808,
            -0.000180149101652205,
            0.0011621289886534214,
            0.0002726432285271585,
            -0.0006086607463657856,
            8.770330168772489e-05,
            0.003294705878943205,
            0.004032519180327654,
            0.00047056993935257196,
            -0.001034081680700183,
            6.792219210183248e-05,
            0.007593856193125248,
        ],
        [
            -0.008890150114893913,
            0.002371471142396331,
            -0.06556080281734467,
            -0.029000308364629745,
            0.10745389759540558,
            0.015305650420486927,
            -0.010970820672810078,
            -0.05827301740646362,
            -0.08139500021934509,
            -0.035574138164520264,
            0.050771377980709076,
            -0.07058624178171158,
            0.06037658452987671,
            0.03544962778687477,
            -0.0014630843652412295,
            0.056947074830532074,
        ],
        [],
    ],
    "one_sided_relu_unconditional": [
        [
            -0.02733730897307396,
            -0.005435906816273928,
            -0.02584305964410305,
            0.00640131114050746,
            8.657516445964575e-05,
            0.0064679901115596294,
            -0.0021774624474346638,
            -0.00020628937636502087,
            -0.0019063680665567517,
            -0.009097947739064693,
            -0.0010004501091316342,
            -0.008176797069609165,
            -0.02730599418282509,
            0.005894573405385017,
            -0.028784330934286118,
            -0.057115066796541214,
            -0.004023422487080097,
            -0.051622334867715836,
            0.03542911261320114,
            -0.0016999549698084593,
            0.03446966037154198,
            0.018439285457134247,
            -0.001727119437418878,
            0.017055528238415718,
            -0.023912696167826653,
            -0.0028959386982023716,
            -0.020487666130065918,
            -0.032272689044475555,
            -0.0050821308977901936,
            -0.03912311792373657,
            -0.03269175440073013,
            -0.009962059557437897,
            -0.034867413341999054,
            -0.04361335188150406,
            -0.0043657864443957806,
            -0.04813561215996742,
            -0.011675446294248104,
            -0.0010849504033103585,
            -0.010509309358894825,
            0.04752034321427345,
            0.004784163553267717,
            0.04159687086939812,
            -0.005366474390029907,
            -0.00046790673513896763,
            -0.004967850167304277,
            0.037177812308073044,
            0.0032743955962359905,
            0.033184945583343506,
        ],
        [
            0.006026241462677717,
            0.00025581353111192584,
            -5.400335066951811e-05,
            0.0003718571679200977,
            -0.012569690123200417,
            -0.001885470119304955,
            0.006133688148111105,
            0.00810256041586399,
            0.00015646233805455267,
            0.01300919707864523,
            0.01785559579730034,
            0.008063999004662037,
            -2.532128564780578e-05,
            0.0004424086946528405,
            0.00019953970331698656,
            0.00024776955251581967,
        ],
        [
            0.0855436623096466,
            0.06677691638469696,
            0.0027997884899377823,
            -0.005549507215619087,
            0.15658465027809143,
            -0.08452688902616501,
            0.03967371582984924,
            -0.18500307202339172,
            -0.09046908468008041,
            0.13862347602844238,
            0.08887936174869537,
            0.18174098432064056,
            0.014259028248488903,
            -0.00459759496152401,
            0.07723048329353333,
            -0.009316523559391499,
        ],
        [],
    ],
    "two_sided_conditional": [
        [
            -0.07819846272468567,
            -0.0500977523624897,
            0.05113569647073746,
            -0.07810493558645248,
            -0.005892407149076462,
            -0.03485247492790222,
            -0.018999075517058372,
            0.01908819191157818,
            -0.03156092017889023,
            -0.0035687738563865423,
            0.12181845307350159,
            0.06131473183631897,
            -0.05973312631249428,
            0.13370375335216522,
            0.020893637090921402,
            0.09390370547771454,
            0.05783359333872795,
            -0.06158919632434845,
            0.09457269310951233,
            -0.0002598455175757408,
            -0.15070627629756927,
            -0.018945269286632538,
            0.08408308774232864,
            -0.13417217135429382,
            0.009054262191057205,
            -0.11177673190832138,
            -0.06696908175945282,
            0.06567922234535217,
            -0.12552371621131897,
            -0.013793700374662876,
            0.07668156176805496,
            0.050266388803720474,
            -0.04607481509447098,
            0.07684152573347092,
            0.00875706784427166,
            0.03633270412683487,
            0.022758498787879944,
            -0.020407993346452713,
            0.05558815225958824,
            0.007426170166581869,
            0.14079946279525757,
            0.017372913658618927,
            -0.0652770847082138,
            0.11565276980400085,
            -0.015386916697025299,
            0.0031194949988275766,
            0.0024012497160583735,
            -0.0019588542636483908,
            0.003647757926955819,
            0.0005548646440729499,
            0.09799350053071976,
            0.018959276378154755,
            -0.07347997277975082,
            0.11846280843019485,
            -0.014031085185706615,
            0.13192404806613922,
            0.08401252329349518,
            -0.0734846219420433,
            0.12731917202472687,
            0.02014962024986744,
            0.00857931561768055,
            0.003466555383056402,
            -0.005673675332218409,
            0.010069102980196476,
            -0.0007256391691043973,
            -0.023752184584736824,
            -0.014119151048362255,
            0.01465767901390791,
            -0.02348041720688343,
            0.00017407536506652832,
            0.060789551585912704,
            0.041928309947252274,
            -0.025281010195612907,
            0.06991726905107498,
            0.013290002942085266,
            -0.08854098618030548,
            -0.05327235162258148,
            0.04982197284698486,
            -0.0949946790933609,
            -0.039000242948532104,
        ],
        [
            0.00567304203286767,
            -0.00297135510481894,
            0.006848364137113094,
            -0.01993608847260475,
            -0.021603062748908997,
            0.00939425639808178,
            -0.004958848934620619,
            -0.009341886267066002,
            0.02469467930495739,
            -0.000550556113012135,
            -0.007232369855046272,
            -0.0002640802413225174,
            -0.0024666152894496918,
            0.003318346105515957,
            -0.0046443636529147625,
            -0.03365383297204971,
        ],
        [
            -0.011494549922645092,
            0.07198496162891388,
            0.22129103541374207,
            0.2516741454601288,
            -0.5275784730911255,
            -0.15878130495548248,
            0.015728313475847244,
            0.35610276460647583,
            0.3782877027988434,
            0.3083013892173767,
            -0.30238404870033264,
            0.28542521595954895,
            -0.4275306761264801,
            -0.1554543823003769,
            0.03173971548676491,
            -0.4405173361301422,
        ],
        [],
    ],
    "two_sided_unconditional": [
        [
            0.10450427234172821,
            0.011993073858320713,
            0.09669945389032364,
            -0.027506617829203606,
            0.005324093624949455,
            -0.026237672194838524,
            0.00791767705231905,
            0.0006182746728882194,
            0.006799669470638037,
            0.042063504457473755,
            -0.0019822397734969854,
            0.03630197420716286,
            0.11005640029907227,
            -0.057120293378829956,
            0.11498674005270004,
            0.2328357845544815,
            -0.01867665722966194,
            0.2002411186695099,
            -0.15765589475631714,
            0.03102574311196804,
            -0.1496814638376236,
            -0.07011913508176804,
            -0.013550356961786747,
            -0.06665454804897308,
            0.09803438186645508,
            0.00014452298637479544,
            0.08031861484050751,
            0.1254929006099701,
            -0.03716418519616127,
            0.1307811290025711,
            0.12096381187438965,
            0.039972055703401566,
            0.12635011970996857,
            0.15491007268428802,
            -0.04380776733160019,
            0.156004399061203,
            0.041783154010772705,
            0.00560206500813365,
            0.03613508492708206,
            -0.21195738017559052,
            -0.00233886088244617,
            -0.17731252312660217,
            0.01827090047299862,
            -0.0006503446493297815,
            0.016324009746313095,
            -0.14353197813034058,
            -0.010381152853369713,
            -0.12222786992788315,
        ],
        [
            -0.01682155206799507,
            -0.0009483098983764648,
            0.0006718087242916226,
            -0.002152323257178068,
            0.021086445078253746,
            -0.006278403103351593,
            -0.022834958508610725,
            -0.02500009536743164,
            -0.008125437423586845,
            -0.044745881110429764,
            -0.0327918604016304,
            -0.04468847066164017,
            0.0019972659647464752,
            -0.0011573821539059281,
            -0.0004047048860229552,
            -0.003955726977437735,
        ],
        [
            -0.36894679069519043,
            -0.2694609463214874,
            -0.023960700258612633,
            0.044531695544719696,
            -0.6195353269577026,
            0.3167021572589874,
            -0.15459446609020233,
            0.7642491459846497,
            0.3533588647842407,
            -0.5070561170578003,
            -0.40228956937789917,
            -0.6229493618011475,
            -0.07645020633935928,
            0.030437391251325607,
            -0.24118877947330475,
            0.004161268472671509,
        ],
        [],
    ],
}


def _run_case(
    conditional: bool, penalty_kwargs: dict[str, Any]
) -> tuple[float, list[list[float]]]:
    """Run one penalty case and return its scalar value and per-parameter gradients."""
    with _single_threaded_torch():
        torch.manual_seed(SEED)  # seed critic init
        d_net = _Critic(conditional)
        generator = torch.Generator().manual_seed(SEED)
        x_gen = torch.randn(BATCH_SIZE, X_SIZE, generator=generator)
        x_data = torch.randn(BATCH_SIZE, X_SIZE, generator=generator)
        y_data = (
            torch.randn(BATCH_SIZE, Y_SIZE, generator=generator)
            if conditional
            else None
        )
        torch.manual_seed(SEED)  # seed interpolation coefficients
        penalty = gradient_penalty(
            d_net, x_gen, x_data, y_data, eager=False, **penalty_kwargs
        )
        penalty.backward()
        # The penalty differentiates the critic's output wrt. its inputs, not
        # wrt. its parameters; the output bias drops out of that derivative,
        # so its `.grad` stays `None` and is frozen here as `[]`
        grads = [
            [] if p.grad is None else p.grad.flatten().tolist()
            for p in d_net.parameters()
        ]
        return penalty.item(), grads


@pytest.mark.parametrize("case_name", list(CASES.keys()))
def test_gradient_penalty_regression(case_name: str) -> None:
    """Reproduce the frozen penalty value and critic gradients for one case."""
    conditional, penalty_kwargs = CASES[case_name]

    value, grads = _run_case(conditional, penalty_kwargs)

    torch.testing.assert_close(
        torch.tensor(value),
        PENALTY_SCALE * torch.tensor(EXPECTED_VALUE[case_name]),
        rtol=REGRESSION_RTOL,
        atol=REGRESSION_ATOL,
    )
    for grad, expected_grad in zip(grads, EXPECTED_GRADS[case_name], strict=True):
        torch.testing.assert_close(
            torch.tensor(grad),
            PENALTY_SCALE * torch.tensor(expected_grad),
            rtol=REGRESSION_RTOL,
            atol=REGRESSION_ATOL,
        )


if __name__ == "__main__":
    # regenerate the expected values, then print them as paste-ready dict
    # literals; undo `PENALTY_SCALE` to keep the frozen values' convention
    print("torch version:", torch.__version__, "| device:", torch.empty(0).device)
    expected_value_ = {}
    expected_grads_ = {}
    for case_name_, (conditional_, penalty_kwargs_) in CASES.items():
        value_, grads_ = _run_case(conditional_, penalty_kwargs_)
        expected_value_[case_name_] = value_ / PENALTY_SCALE
        expected_grads_[case_name_] = [
            [g / PENALTY_SCALE for g in grad_] for grad_ in grads_
        ]
    print(f"EXPECTED_VALUE = {expected_value_!r}")
    print(f"EXPECTED_GRADS = {expected_grads_!r}")
